// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoolXLWsHcWVwqekEL1RfeBA2XedTyVP0',
    appId: '1:836150243114:web:04d7790c715cede054b853',
    messagingSenderId: '836150243114',
    projectId: 'leaveapp-ec06c',
    authDomain: 'leaveapp-ec06c.firebaseapp.com',
    storageBucket: 'leaveapp-ec06c.appspot.com',
    measurementId: 'G-C21K3R6BX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-94ho1H3VkOzlzuVsjDQlQHGAgruzuqI',
    appId: '1:836150243114:android:928a40e7bb007b1954b853',
    messagingSenderId: '836150243114',
    projectId: 'leaveapp-ec06c',
    storageBucket: 'leaveapp-ec06c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXS-nmKCTWSrMBDr5cKtH9oLjpITtzBdM',
    appId: '1:836150243114:ios:e3c7c0227575509954b853',
    messagingSenderId: '836150243114',
    projectId: 'leaveapp-ec06c',
    storageBucket: 'leaveapp-ec06c.appspot.com',
    iosClientId: '836150243114-mjfouqvi50f43jeoq37jead76ldkqknc.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaveapp',
  );
}
